openapi: 3.0.0
info:
  title: Paysolutions-external-api
  version: 1.0.0
servers:
  - url: https://apis.paysolutions.asia
paths:
  /order/orderdetailpost:
    post:
      tags:
        - default
      summary: Inquiry-order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                merchantId: '{{merchantid}}'
                orderNo: x
                refNo: x
                productDetail: QWERTY
      parameters:
        - name: merchantId
          in: header
          schema:
            type: string
          example: '{{merchantid}}'
        - name: merchantSecretKey
          in: header
          schema:
            type: string
          example: '{{merchant_secret_key}}'
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{merchant_api_key}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
