openapi: 3.0.0
info:
  title: Paysolutions External API
  version: 1.0.0
servers:
  - url: https://apis.paysolutions.asia
paths:
  /order/orderdetailpost:
    post:
      tags:
        - default
      summary: Inquiry Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/OrderRequest'
      parameters:
        - name: merchantId
          in: header
          schema:
            type: string
          example: '12345'
        - name: merchantSecretKey
          in: header
          schema:
            type: string
          example: 'saedewrtWsdf42'
        - name: apikey
          in: header
          schema:
            type: string
          example: 'asdewrP2'
      responses:
        '200':
          description: A list of Order.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
components:
  schemas:
    OrderRequest: # Schema name
      type: object
      properties:
        merchantId:
          type: string
        orderNo:
          type: string
        refNo:
          type: string
        productDetail:
          type: string   
      example:   # Object-level example
        merchantId: '12345'
        orderNo: 'x when not use to inquery data' 
        refNo:  'x when not use to inquery data' 
        productDetail : 'QWERTY when not use to inquery data'
    OrderResponse: # Schema name
      type: object
      properties:
        ReferenceNo:
          type: string
        OrderNo:
          type: string
        MerchantID:
          type: string
        Total:
          type: number
        CardType:
          type: string
        CustomerEmal:
          type: string
        CurrencyCode:
          type: string
        Status:
          type: string
        StatusName:
          type: string
        PostBackUrl:
          type: string
        PostBackParameters:
          type: string 
        PostBackMethod:
          type: string 
        PostBackCompleted:
          type: string 
        OrderDateTime:
          type: string
        installment:
          type: string
      example:   # Object-level example
         ReferenceNo: "869331151059"
         OrderNo: "012345666"
         MerchantID: "99999999"
         ProductDetail: "Some Product Dtail"
         Total: 3900.0
         CardType: "V"
         CustomerEmail: "some_customer@mail.com"
         CurrencyCode: "OO"
         Status: "CP"
         StatusName: "COMPLETE"
         PostBackUrl: "https://someweb.com?postback=1"
         PostBackParameters: "COMPLETED"
         PostBackMethod: "P"
         PostBackCompleted: "true"
         OrderDateTime: "2020-10-05T03:48:11.990+00:00"
         installment: null
